FROM node:18-alpine AS builder

WORKDIR /app

# copy package files
COPY app/package*.json ./

# 🔥 FIX HERE
RUN npm install --legacy-peer-deps

# copy full app
COPY app/ .

RUN npm run build

FROM node:18-alpine
WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000
CMD ["npm", "start"]
