FROM node:18-alpine AS builder

WORKDIR /app

# copy only package files first
COPY app/package*.json ./
RUN npm install

# copy full app
COPY app/ .

RUN npm run build

FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app ./

EXPOSE 3000
CMD ["npm", "start"]
